# Generated by Django 5.0.6 on 2024-05-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='registered',
            field=models.BooleanField(default=True),
        ),
    ]
