# Generated by Django 5.0.6 on 2024-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_payment_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='additional_info',
            field=models.TextField(),
        ),
    ]
